jobs:
  ci:
    uses: killbill/gh-actions-shared/.github/workflows/ci.yml@main
  e2e:
    runs-on: self-hosted
    services:
      mysql:
        env:
          MYSQL_ROOT_PASSWORD: root
        image: mysql:8.0
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s
          --health-retries=10
        ports:
        - 3306:3306
    steps:
    - continue-on-error: true
      name: Checkout killbill
      uses: actions/checkout@v2.4.0
      with:
        persist-credentials: false
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v2.5.0
      with:
        distribution: ${{ matrix.java-distribution }}
        java-version: ${{ matrix.java-version }}
    - continue-on-error: true
      name: Configure Sonatype mirror
      uses: s4u/maven-settings-action@v2.4.1
      with:
        mirrors: '[{"id": "oss-releases", "name": "Sonatype releases", "mirrorOf":
          "central", "url": "https://oss.sonatype.org/content/repositories/releases"}]'
        sonatypeSnapshots: true
    - continue-on-error: true
      name: Set up Maven
      run: mvn --errors --batch-mode --show-version wrapper:wrapper "-Dmaven=${{ matrix.maven_version
        }}"
    - continue-on-error: true
      name: Build Kill Bill
      run: ./mvnw --errors --batch-mode --show-version clean install -DskipTests=true
        -Dcheck.skip-dependency=true -Dcheck.skip-dependency-scope=true -Dcheck.skip-dependency-versions=true
        -Dcheck.skip-duplicate-finder=true -Dcheck.skip-enforcer=true -Dcheck.skip-rat=true
        -Dcheck.skip-spotbugs=true
    - continue-on-error: true
      if: ${{ matrix.database == 'mysql' }}
      name: Wait for MySQL
      run: "set +e\ncount=0\nuntil mysqladmin ping -h 127.0.0.1 -u root --password=root\
        \ --silent; do\n  if [[ \"$count\" == \"25\" ]]; then\n    exit 1\n  fi\n\
        \  (( count++ ))\n  printf '.'\n  sleep 5\ndone\nset -e\n"
    - continue-on-error: true
      if: ${{ matrix.database == 'postgresql' }}
      name: Wait for PostgreSQL
      run: "set +e\ncount=0\nuntil $(psql -h 127.0.0.1 -U postgres -p 5432 -l > /dev/null);\
        \ do\n  if [[ \"$count\" == \"25\" ]]; then\n    exit 1\n  fi\n  (( count++\
        \ ))\n  printf '.'\n  sleep 5\ndone\nset -e\n"
    - continue-on-error: true
      if: ${{ matrix.database == 'mysql' }}
      name: Setup latest DDL
      run: 'mysql -h 127.0.0.1 -u root --password=root -e ''create database killbill''

        ./bin/db-helper -a create --driver mysql -u root -p root -t yes -h 127.0.0.1

        '
    - continue-on-error: true
      if: ${{ matrix.database == 'postgresql' }}
      name: Setup latest DDL
      run: 'psql -h 127.0.0.1 -U postgres -p 5432 -c ''create database killbill''

        ./bin/db-helper -a create --driver postgres -u postgres -t yes -h 127.0.0.1
        --port 5432

        '
    - continue-on-error: true
      if: ${{ matrix.database == 'mysql' }}
      name: Install plugin specific MySQL DDL
      run: 'curl https://raw.githubusercontent.com/killbill/killbill-avatax-plugin/master/src/main/resources/ddl.sql
        | mysql -h 127.0.0.1 -u root --password=root killbill

        curl https://raw.githubusercontent.com/killbill/killbill-payment-test-plugin/master/src/main/resources/ddl.sql
        | mysql -h 127.0.0.1 -u root --password=root killbill

        curl https://raw.githubusercontent.com/killbill/killbill-email-notifications-plugin/master/src/main/resources/ddl.sql
        | mysql -h 127.0.0.1 -u root --password=root killbill

        '
    - continue-on-error: true
      if: ${{ matrix.database == 'postgresql' }}
      name: Install plugin specific PostgreSQL DDL
      run: 'curl https://raw.githubusercontent.com/killbill/killbill-avatax-plugin/master/src/main/resources/ddl.sql
        | psql -h 127.0.0.1 -U postgres -p 5432 -d killbill

        curl https://raw.githubusercontent.com/killbill/killbill-payment-test-plugin/master/src/main/resources/ddl.sql
        | psql -h 127.0.0.1 -U postgres -p 5432 -d killbill

        curl https://raw.githubusercontent.com/killbill/killbill-email-notifications-plugin/master/src/main/resources/ddl.sql
        | psql -h 127.0.0.1 -U postgres -p 5432 -d killbill

        '
    - continue-on-error: true
      name: Start Kill Bill
      run: "mkdir -p /tmp/test-results\nnohup ./bin/start-server -s > /tmp/test-results/killbill.log\
        \ 2>&1 &\ncount=0\nuntil $(curl --connect-timeout 10 --max-time 30 --output\
        \ /dev/null --silent --fail http://127.0.0.1:8080/1.0/healthcheck); do\n \
        \ if [[ \"$count\" == \"180\" ]]; then\n    exit 64\n  fi\n  count=$(( count\
        \ + 1 ))\n  sleep 1\ndone\ncurl --connect-timeout 10 --max-time 30 -v \\\n\
        \     -X POST \\\n     -u admin:password \\\n     -H 'Content-Type: application/json'\
        \ \\\n     -H 'X-Killbill-CreatedBy: GitHub' \\\n     -d '{\"apiKey\": \"\
        bob\", \"apiSecret\": \"lazar\"}' \\\n     \"http://127.0.0.1:8080/1.0/kb/tenants\"\
        \n"
      timeout-minutes: 4
    - continue-on-error: true
      name: Checkout killbill-integration-tests
      uses: actions/checkout@v2
      with:
        path: killbill-integration-tests
        persist-credentials: false
        ref: ${{ matrix.ref }}
        repository: killbill/killbill-integration-tests
    - continue-on-error: true
      name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ${{ matrix.ruby-version }}
        working-directory: ${{github.workspace}}/killbill-integration-tests
    - continue-on-error: true
      name: Install dependencies
      run: 'bundle install --jobs=4 --retry=3

        '
      working-directory: ${{github.workspace}}/killbill-integration-tests
    - continue-on-error: true
      env:
        DB_ADAPTER: ${{ matrix.database-adapter }}
        DB_PASSWORD: ${{ matrix.database-password }}
        DB_PORT: ${{ matrix.database-port }}
        DB_USER: ${{ matrix.database-user }}
      name: Run core tests
      run: 'bundle exec rake test:core TESTOPTS="--stop-on-failure"

        '
      working-directory: ${{github.workspace}}/killbill-integration-tests
    - continue-on-error: true
      if: failure()
      name: Upload artifact on failure
      uses: actions/upload-artifact@v2.3.1
      with:
        name: failure-${{ matrix.database }}
        path: /tmp/test-results/killbill.log
    strategy:
      matrix:
        include:
        - database: mysql
          database-adapter: mysql2
          database-password: root
          database-port: '3306'
          database-user: root
          java-distribution: temurin
          java-version: '11'
          maven_version: 3.8.4
          ref: refs/heads/master
          ruby-version: 2.5.0
name: ci
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
